# Use an official Python runtime as a base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current project files to the container
COPY . /app

# Install required system dependencies and Python dependencies, and download NLTK data
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/* \
    && pip install --no-cache-dir -r requirements.txt \
    && python -m nltk.downloader punkt -d /usr/share/nltk_data

# Expose a port (optional, if running a server)
EXPOSE 8080

# Define the command to run the app
CMD ["python", "main.py"]

